### ISSUE TITLE
Question about "ModuleNotFoundError: No module named 'igl'"

### ISSUE THREAD

**Issue by DTliudong** [apple/ml-neuman#10]
Thanks for releasing this excellent work!
I am trying to reproduce the results. However I meet the problem as follows.
When I run:
python render_360.py --scene_dir ./data/bike --weights_path ./out/bike_human/checkpoint.pth.tar --mode canonical_360
It shows:
Traceback (most recent call last):
  File "render_360.py", line 20, in <module>
    from cameras.captures import ResizedPinholeCapture
  File "/home/liudong/ml-neuman/cameras/captures.py", line 15, in <module>
    from utils import ray_utils
  File "/home/liudong/ml-neuman/utils/ray_utils.py", line 7, in <module>
    import igl
ModuleNotFoundError: No module named 'igl'

I try to run 'conda list' and it shows I have installed igl 

_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2022.6.15        py37h89c1867_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cudatoolkit               11.1.1              ha002fc5_10    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.12.1               hca18f0e_0    conda-forge
fvcore                    0.1.5.post20210915            py37    fvcore
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
igl                       2.2.1            py37h9d0810c_1    conda-forge
iopath                    0.1.9                      py37    iopath
jpeg                      9b                   h024ee3a_2    defaults
lame                      3.100             h7f98852_1001    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0            12_linux64_mkl    conda-forge
libcblas                  3.9.0            12_linux64_mkl    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0            12_linux64_mkl    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               h753d276_4    conda-forge
libsqlite                 3.39.2               h753d276_1    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.0.9                he6b73bb_1    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
mkl                       2021.4.0           h8d4b97c_729    conda-forge
mkl-service               2.4.0            py37h402132d_0    conda-forge
mkl_fft                   1.3.1            py37h3e078e5_1    conda-forge
mkl_random                1.2.2            py37h219a48f_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
numpy                     1.21.5           py37h6c91a56_3    defaults
numpy-base                1.21.5           py37ha15fc14_3    defaults
nvidiacub                 1.10.0                        0    bottler
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   3.0.5                h166bdaf_1    conda-forge
pillow                    5.4.1            py37h34e0f95_0    defaults
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
portalocker               2.5.1            py37h89c1867_0    conda-forge
python                    3.7.12          hf930737_100_cpython    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.8.0           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
pytorch3d                 0.7.0           py37_cu111_pyt180    pytorch3d
pyyaml                    6.0              py37h540881e_4    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
scipy                     1.7.3            py37hf2a6cf1_0    conda-forge
setuptools                65.2.0           py37h89c1867_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.39.2               h4ff8645_1    conda-forge
tabulate                  0.8.10             pyhd8ed1ab_0    conda-forge
tbb                       2021.5.0             h924138e_1    conda-forge
termcolor                 1.1.0              pyhd8ed1ab_3    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
torchaudio                0.8.0                      py37    pytorch
torchvision               0.9.0                py37_cu111    pytorch
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge

**Comment by jiangwei221** [comment]
can you try ```conda install -c conda-forge igl```?

**Comment by DTliudong** [comment]
> 



> can you try `conda install -c conda-forge igl`?

yes.

**Comment by DTliudong** [comment]
> 

I try the 'conda install -c conda-forge igl' and it shows 'All requested packages already installed.'

**Comment by jiangwei221** [comment]
yeah, env.yaml sometimes doesn't work well, you probably want to manually run `conda install` as stated in the readme.

**Comment by jiangwei221** [comment]
hmmmmm, can you try `which python` and `which pip`?

**Comment by DTliudong** [comment]
> hmmmmm, can you try `which python` and `which pip`?

Thanks for your help,I tried to restart my machine and the problem disappeared. Restart can solve most strange problems.
