### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by APeiZou** [apple/ml-neuman#11]
@federicobucchi @rwebb @kolecke  hello  ， when  I run python render_reposing.py --scene_dir ./data/bike --weights_path ./out/bike_human/checkpoint.pth.tar --motion_name=jumpandroll 
 ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found？

**Comment by norris9410** [comment]
I encounter the same error. Any idea how to resolved this problem?
