### ISSUE TITLE
Is there a demo that generates any human pose on a custom dataset ?

### ISSUE THREAD

**Issue by APeiZou** [apple/ml-neuman#13]
@federicobucchi @rwebb @kolecke  Hello,   Is there a demo that generates any human pose on a custom dataset?

**Comment by jiangwei221** [comment]
Hi @APeiZou, can you detail your question? The provided dataset and the custom dataset should have the same format, i.e. what we show in the paper, should also be doable on a custom dataset.

**Comment by APeiZou** [comment]
@jiangwei221 ,Hello, thank you for your reply is there a pipeline demo scripte to prepare my custom dataset?

**Comment by jiangwei221** [comment]
You can have a look at: https://github.com/apple/ml-neuman/tree/main/preprocess

**Comment by APeiZou** [comment]
thanks a lot @jiangwei221
