### ISSUE TITLE
 There was a problem running colmap on a custom dataset.  No good initial image pair found.

### ISSUE THREAD

**Issue by APeiZou** [apple/ml-neuman#15]
@jiangwei121，  Hello， In my dataset the scene hardly changes. There was a problem when I running colmap on a custom dataset.  No good initial image pair found? Is there any good solution?

**Comment by jiangwei221** [comment]
I guess you mean the camera is not moving in your video?
We rely on Structure-from-Motion software(COLMAP) to obtain the camera poses and sparse scene point cloud, if there is no camera motion(assuming the world is stationary), COLMAP will fail.
I suggest that you can add some **translation and rotation** to the camera motion, pure rotation will also cause bad reconstruction. For example, you can walk together with the subject.

**Comment by APeiZou** [comment]
@jiangwei221  Thank you for your reply. I guess so too. I will close this issue.
