### ISSUE TITLE
Some confusion about the smpl results in the preprocessing

### ISSUE THREAD

**Issue by yijicheng** [apple/ml-neuman#17]
Thanks for your excellent work!

I found the smpl results provided in the github can not be reproduced following `gen_run.py`. Are there any extra procedures?

**Comment by jiangwei221** [comment]
Do you mean the SMPL results on the provided dataset or on custom data? Can you provide some comparisons?

**Comment by yijicheng** [comment]
On the provided dataset.
![image](https://user-images.githubusercontent.com/53086386/187070741-f18e0ed8-00d0-4ae5-8bc2-6a25d009dfb7.png)

**Comment by jiangwei221** [comment]
In the `overlay` folder, there should be two sub-folders, one is `romp`, and one is `optimized`. Can you also provide the overlays before and after optimization?

**Comment by yijicheng** [comment]
> In the `overlay` folder, there should be two sub-folders, one is `romp`, and one is `optimized`. Can you also provide the overlays before and after optimization?

![image](https://user-images.githubusercontent.com/53086386/187078341-9f39f359-33f6-4d58-938f-30fc13edfdab.png)

**Comment by jiangwei221** [comment]
![Screenshot from 2022-08-28 08-03-00](https://user-images.githubusercontent.com/25207535/187080760-c6ff7967-a581-4d67-9e19-e537be118f49.png)
This is a new run from my end, the left one is `romp`, and the right one is `optimized`, it seems to be ok.
One thing to note is that I didn't colmap again, and I only rerun the SMPL estimates, scale estimation, and SMPL optimization. Did you rerun colmap in your case?

**Comment by yijicheng** [comment]
> ![Screenshot from 2022-08-28 08-03-00](https://user-images.githubusercontent.com/25207535/187080760-c6ff7967-a581-4d67-9e19-e537be118f49.png) This is a new run from my end, the left one is `romp`, and the right one is `optimized`, the feet seem to be ok. One thing to note is that I didn't run colmap again, and I only rerun the SMPL estimates, scale estimation, and SMPL optimization. Did you rerun colmap in your case? To optimize the hand and head, you probably need to enable the gradient w.r.t that joint in `turn_smpl_gradient_on` function.

Thanks for your patient answer!

It seems that smpl head joint can not be aligned with coco 2d keypoint? how can I turn on head joint?

**Comment by jiangwei221** [comment]
Can you show the results of coco2d of this image?
To enable the head joint, add one more if statement in `turn_smpl_gradient_on` function.
The if statement should be something like: 
```python
if 'Head' in visible"
    grad_mask[15] = 1
```

**Comment by yijicheng** [comment]
> Can you show the results of coco2d of this image? To enable the head joint, add one more if statement in `turn_smpl_gradient_on` function. The if statement should be something like:
> 
> ```python
> if 'Head' in visible:
>     grad_mask[15] = 1
> ```

![image](https://user-images.githubusercontent.com/53086386/187108545-e29ccce1-a59c-488d-a89b-cf3824441752.png)

**Comment by jiangwei221** [comment]
I think you are correct. COCO2D joint annotation is not a 1-to-1 match to SMPL joints, it depends on how each dataset defines the joints. Here's the mapping we used: https://github.com/apple/ml-neuman/blob/b5a9dae87e300a34412d18ced0ecafacc2cd6e07/preprocess/optimize_smpl.py#L33-L53
For example, there is no mapping for the head joint for COCO2D. But it shouldn't be fine for the silhouette loss to work.

**Comment by yijicheng** [comment]
I clone the code and download data again, but still get bad results. Should I tune the learning rate of the optimization?

**Comment by jiangwei221** [comment]
> I clone the code and download data again, but still get bad results. Should I tune the learning rate of the optimization?
> 
> ![image](https://user-images.githubusercontent.com/53086386/187112069-5d8baf75-a0cb-4bc0-897f-ccb374fadb6a.png)

I also used the default configuration at my end. In your case, did you rerun colmap+densepose+maskrcnn?

**Comment by jiangwei221** [comment]
hmmmmmm... yeah, I think tuning down the learning rate probably helps.

**Comment by buaacyw** [comment]
Hi! I also rerun the ROMP + alignment + optimization on this data and get the same result with @yijicheng.
Is this caused by different random seeds? Otherwise I can't figure out the reason.

**Comment by buaacyw** [comment]
I have tried to tune the learning rate of step10 (optimize smpl). But it didn't work.

**Comment by jiangwei221** [comment]
whaaaaaaat, maybe because of different GPUs?

**Comment by buaacyw** [comment]
> 

I think that may not be a big problem. Only the result of 0014.png in Seattle is largely different. Other results are nice. 
I'm using A5000.
