### ISSUE TITLE
Question about the TRAIN_SET_LENGTH constant value

### ISSUE THREAD

**Issue by yaoyuan13** [apple/ml-neuman#18]
Hi, thanks for open-source the excellent work.

I have a question that In dataset code, why use a large number TRAIN_SET_LENGTH=1000000 to represent the length of the training set, such that the training epoch [(max_epoch)](https://github.com/apple/ml-neuman/blob/b5a9dae87e300a34412d18ced0ecafacc2cd6e07/trainers/human_nerf_trainer.py#L186) is always be 1 for both background and human nerf training. Any consideration for this value?  Thanks.

**Comment by jiangwei221** [comment]
At each iteration, we randomly select pixels to render. Therefore the epoch doesn’t mean too much in our case, in term of the coverage of the data distribution.

**Comment by yaoyuan13** [comment]
It solves my concern, thanks.
