### ISSUE TITLE
Can you provide the original demo video?

### ISSUE THREAD

**Issue by yijicheng** [apple/ml-neuman#2]
Thanks for your excellent work! Can you provide the original demo video?

**Comment by jiangwei221** [comment]
Do you mean the raw videos we took?

**Comment by yijicheng** [comment]
> Do you mean the raw videos we took?

yes！

**Comment by jiangwei221** [comment]
Hi @yijicheng, we can't share the raw video at the moment.

**Comment by yijicheng** [comment]
> Hi @yijicheng, we can't share the raw video at the moment.
Thanks for your reply!
