### ISSUE TITLE
Code of rendering background scenes

### ISSUE THREAD

**Issue by Nuyoah13** [apple/ml-neuman#20]
Thanks for releasing this excellent work!

I am reproducing the results following your two stage training instructions. After training, I see there are some artifacts in  background when rendering test view results, and want to render the background scene using the scene model to see bg reconstruction results separately.  I have found no code release of the rendering and try to implement myself, but the result is not correct though.

Could you please release the code for rendering background scene? Thanks.

**Comment by Nuyoah13** [comment]
Solved, thanks.

**Comment by zjj421** [comment]
how did you solve this, Can you share the code to render the background scene with the trained  custom scene model?

**Comment by jiangwei221** [comment]
You can use the following code snippet: https://github.com/apple/ml-neuman/blob/0149d258b2afe6ef65c91557bba9f874675871e4/trainers/vanilla_nerf_trainer.py#L155-L165
