### ISSUE TITLE
No parkinglot_rotate in pretrained.zip

### ISSUE THREAD

**Issue by Ruyi-Zha** [apple/ml-neuman#23]
Thanks for the great work.

I tried to render telegathering with command `python render_gathering.py --actors parkinglot seattle citron --scene_dir ./data/seattle --weights_path ./out/seattle_human/checkpoint.pth.tar` but failed with `No such file or directory: './out/parkinglot_rotate/checkpoint.pth.tar'`. It looks like that `parkinglot_rotate` is not included in `pretrained.zip`. Do we have to train parkinglot_rotate by ourselves?

**Comment by jiangwei221** [comment]
You can check the latest patch #24.
