### ISSUE TITLE
How is the 2D field of view angle of secen nerf model obtained? Is the 2D field of view angle of secen nerf model the same as that of human nerf?

### ISSUE THREAD

**Issue by APeiZou** [apple/ml-neuman#25]
@jiangwei221  Hello,  How is the 2D field of view angle of secen nerf model obtained? Is the 2D field of view angle of secen nerf model the same as that of human nerf?

**Comment by jiangwei221** [comment]
The camera intrinsics are obtained from COLMAP. We use the same camera intrinsics when training scene nerf and human nerf.

**Comment by APeiZou** [comment]
@jiangwei221 What is the specific relationship between camera intrinsics participation and 2D field of view angle? It should be a camera Extrinsics.
