### ISSUE TITLE
The reconstructed human model are not good for custom data

### ISSUE THREAD

**Issue by yaoyuan13** [apple/ml-neuman#27]
Hi， 
I try to train your model after following the data processing procedure for custom data, the processed results seems correct, but the reconstruction of human models are not good, with blurry and ghosting effects，a large gap with your present results.  Any issues may lead to this phenomenon？Any tips for training a good model? Thanks

**Comment by jiangwei221** [comment]
Can you share some scene-SMPL alignment visualization, SMPL overlay, and tensorboard screenshots(scalar and image) for both scene and human models?
