### ISSUE TITLE
Dockerfile might need editing for cuda-pytorch compatibility

### ISSUE THREAD

**Issue by domattioli** [apple/ml-neuman#29]
I'm running through the commands of your [PreProcess Readme](https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/preprocess/README.md) and everything runs well until the `bash -i ./run.sh` command.

The process freezes within the terminal, throwing a warning that my PyTorch installation is incompatible with my CUDA capability:
```
[09/13 20:37:07 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='../configs/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml', input=['/neuman/data/my_video/my_example_video/raw_720p/00000.png', '/neuman/data/my_video/my_example_video/raw_720p/00001.png', '/neuman/data/my_video/my_example_video/raw_720p/00002.png', '/neuman/data/my_video/my_example_video/raw_720p/00003.png', '/neuman/data/my_video/my_example_video/raw_720p/00004.png', '/neuman/data/my_video/my_example_video/raw_720p/00005.png', '/neuman/data/my_video/my_example_video/raw_720p/00006.png', '/neuman/data/my_video/my_example_video/raw_720p/00007.png', '/neuman/data/my_video/my_example_video/raw_720p/00008.png', '/neuman/data/my_video/my_example_video/raw_720p/00009.png', '/neuman/data/my_video/my_example_video/raw_720p/00010.png', '/neuman/data/my_video/my_example_video/raw_720p/00011.png', '/neuman/data/my_video/my_example_video/raw_720p/00012.png', '/neuman/data/my_video/my_example_video/raw_720p/00013.png', '/neuman/data/my_video/my_example_video/raw_720p/00014.png', '/neuman/data/my_video/my_example_video/raw_720p/00015.png', '/neuman/data/my_video/my_example_video/raw_720p/00016.png', '/neuman/data/my_video/my_example_video/raw_720p/00017.png', '/neuman/data/my_video/my_example_video/raw_720p/00018.png', '/neuman/data/my_video/my_example_video/raw_720p/00019.png', '/neuman/data/my_video/my_example_video/raw_720p/00020.png', '/neuman/data/my_video/my_example_video/raw_720p/00021.png', '/neuman/data/my_video/my_example_video/raw_720p/00022.png', '/neuman/data/my_video/my_example_video/raw_720p/00023.png', '/neuman/data/my_video/my_example_video/raw_720p/00024.png', '/neuman/data/my_video/my_example_video/raw_720p/00025.png', '/neuman/data/my_video/my_example_video/raw_720p/00026.png', '/neuman/data/my_video/my_example_video/raw_720p/00027.png', '/neuman/data/my_video/my_example_video/raw_720p/00028.png', '/neuman/data/my_video/my_example_video/raw_720p/00029.png', '/neuman/data/my_video/my_example_video/raw_720p/00030.png', '/neuman/data/my_video/my_example_video/raw_720p/00031.png'], opts=['MODEL.WEIGHTS', './model_final_2d9806.pkl'], output='/neuman/data/my_video/my_example_video/raw_masks', video_input=None, webcam=False)
/opt/conda/envs/ROMP/lib/python3.8/site-packages/torch/cuda/__init__.py:106: UserWarning:
NVIDIA RTX A5000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA RTX A5000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
```

While I did need to make sure that my pytorch installation was installed using the locally instructions, I've had no issues running the Demo instructions for the rendering. I'm wondering whether your dockerfile needs alteration and/or your readme needs to mention that this an error is possible without changing the dockerfile instructions.

Edit - pertinent venv library versions:
```
cudatoolkit               11.3.1               h2bc3f7f_2
nvidiacub                 1.10.0                        0    bottler
python                    3.7.13               h12debd9_0
pytorch                   1.12.1          py3.7_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytorch3d                 0.7.0           py37_cu113_pyt1121    pytorch3d
torchaudio                0.12.1               py37_cu113    pytorch
torchvision               0.13.1               py37_cu113    pytorch
```

**Comment by jiangwei221** [comment]
Hi @domattioli, RTX 30 series and A5000 GPUs require CUDA11.x, but in the Dockerfile, I used CUDA10.x and tested with RTX 2060 GPU, so there's a mismatch in the environment, i.e. cudatoolkit version. If you have a machine with older GPUs, the Dockerfile should work. Currently, I don't have newer GPUs at hand or sudo privilege on the server, so I can't test it.

**Comment by domattioli** [comment]
Update: ~30 minutes later the terminal unfroze and continued running the script to write geometric output for all of my images. Ran for about 10 minutes (31 .pngs), then again froze. Seems to be only an inconvenient warning, not a fatal error.

Your explanation makes sense and I figured as much. Just wanted to document it.

**Comment by domattioli** [comment]
For docker-novices like myself wanting to change the dockerfile to reflect the appropriate CUDA:

I've changed the first line to reflect my needs to `FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04`.

I also changed the `conda install` line in the # ROMP, # mmpose, and # neuman environment sections to:
```
conda install -c pytorch pytorch=1.11 torchvision torchaudio cudatoolkit=11.3 &&
```

Lastly, I replace the mmcv install command according to [these instructions](https://github.com/open-mmlab/mmcv). The image is then successfully built.

Edit: my version of the docker file attached:
[Dockerfile-edited_for_CUDA113.txt](https://github.com/apple/ml-neuman/files/9627442/Dockerfile-edited_for_CUDA113.txt)

**Comment by lxxue** [comment]
> For docker-novices like myself wanting to change the dockerfile to reflect the appropriate CUDA:
> 
> I've changed the first line to reflect my needs to `FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04`.
> 
> I also changed the `conda install` line in the # ROMP, # mmpose, and # neuman environment sections to:
> 
> ```
> conda install -c pytorch pytorch=1.11 torchvision torchaudio cudatoolkit=11.3 &&
> ```
> 
> Lastly, I replace the mmcv install command according to [these instructions](https://github.com/open-mmlab/mmcv). The image is then successfully built.
> 
> Edit: my version of the docker file attached: [Dockerfile-edited_for_CUDA113.txt](https://github.com/apple/ml-neuman/files/9627442/Dockerfile-edited_for_CUDA113.txt)

Thanks for providing the modified Dockerfile. In my case, I add another two fixes to make things work on my machine:

* specify the version of `mmcv-full` to 1.5.0 to make it compatible with `mmpose`. Change it from 
```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html
```
to (modifed based on the following comments)

<pre><code><del>
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/mmcv_full-1.5.0-cp37-cp37m-manylinux1_x86_64.whl
</del>
pip install mmcv-full==1.5.0
</code></pre>

* Add flag `--no-check-certificate` for `wget` when getting the checkpoint of `BoostingMonocularDepth`:
https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/preprocess/gen_run.py#L114

**Comment by domattioli** [comment]
> 

How do you add the `--no-check-certificate` flag to this line? Between the wget and the https? That's where I put it yet my output still shows the wrong version:
```
========================================
6/10: 2D keypoints
========================================
Traceback (most recent call last):
  File "demo/bottom_up_img_demo.py", line 10, in <module>
    from mmpose.apis import (inference_bottom_up_pose_model, init_pose_model,
  File "/neuman/preprocess/mmpose/mmpose/__init__.py", line 26, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.6.1 is used but incompatible. Please install mmcv>=1.3.8, <=1.5.0.
```

**Comment by lxxue** [comment]
Yes that's where `--no-check-certificate` should be. This flag helps you download the checkpoint `latest_net_G.pth`. 

In my opinion, this flag has nothing to do with the error you get. I don't know if you redo the `docker build` completely or you just start from the old container and reexecute certain commands. I would suggest you to execute these two commands in the current built container:
```
# fully uninstall 1.6.1 version, otherwise pip install will tell you that you have installed the pkg
pip uninstall mmcv-full 
# install the correct version
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/mmcv_full-1.5.0-cp37-cp37m-manylinux1_x86_64.whl
```

**Comment by domattioli** [comment]
I inserted your suggested code into the Dockerfile and re-ran the docker build. However, I'm still getting the same error and the open-mmlab environment within the container still shows mmcv-full=1.6.1.

Here is the [output](https://github.com/apple/ml-neuman/files/9669720/open-mmlab.conda.list.txt) for `conda list` within the docker container.

Running the same two commands from your prior comment still results in mmcv-full-1.6.1 installing...
```
(open-mmlab) root@f3fdf5d3629f:/neuman/preprocess# pip uninstall mmcv-full
Found existing installation: mmcv-full 1.6.1
Uninstalling mmcv-full-1.6.1:
  Would remove:
    /opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/*
    /opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv_full-1.6.1.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled mmcv-full-1.6.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(open-mmlab) root@f3fdf5d3629f:/neuman/preprocess# pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/mmcv_full-1.5.0-cp37-cp37m-manylinux1_x86_64.whl
Looking in links: https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/mmcv_full-1.5.0-cp37-cp37m-manylinux1_x86_64.whl
WARNING: Skipping page https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/mmcv_full-1.5.0-cp37-cp37m-manylinux1_x86_64.whl because the HEAD request got Content-Type: application/octet-stream.The only supported Content-Type is text/html
Collecting mmcv-full
  Using cached mmcv_full-1.6.1-cp37-cp37m-linux_x86_64.whl
Requirement already satisfied: yapf in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (0.32.0)
Requirement already satisfied: packaging in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (21.3)
Requirement already satisfied: Pillow in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (9.2.0)
Requirement already satisfied: addict in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (2.4.0)
Requirement already satisfied: numpy in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (1.21.5)
Requirement already satisfied: pyyaml in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (6.0)
Requirement already satisfied: opencv-python>=3 in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (4.6.0.66)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from packaging->mmcv-full) (3.0.9)
Installing collected packages: mmcv-full
Successfully installed mmcv-full-1.6.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

 Any suggestions?

**Comment by lxxue** [comment]
I think this message tells you that you installed 1.6.1 again:
```
WARNING: Skipping page https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/mmcv_full-1.5.0-cp37-cp37m-manylinux1_x86_64.whl because the HEAD request got Content-Type: application/octet-stream.The only supported Content-Type is text/html
Collecting mmcv-full
  Using cached mmcv_full-1.6.1-cp37-cp37m-linux_x86_64.whl
```
I tried some commands locally and found that you could install the correct one by simply specifying the version: 
`pip install mmcv-full==1.5.0`

**Comment by JacCubk** [comment]
I installed using a new Docker file on a 30 series graphics card and received an unexpected error. Please record it here for those in need. I encountered an error while using the Docker file, but replacing the Python version in the ROMP environment with 3.9 can solve this problem.

**Comment by hrx20000209** [comment]
Hi, thanks for sharing. I have used your file, but it comes out like this:
```
Dockerfile:98
--------------------
  97 |     # ROMP environment
  98 | >>> RUN . /root/.bashrc && \
  99 | >>>     conda create -n ROMP python==3.8.8 && \
 100 | >>>     conda activate ROMP && \
 101 | >>> #    conda install -c pytorch pytorch=1.9.1 torchvision=0.10.1 cudatoolkit=10.2 && \
 102 | >>>     conda install -c pytorch pytorch=1.11 torchvision torchaudio cudatoolkit=11.3 && \
 103 | >>>     conda install -c fvcore -c iopath -c conda-forge fvcore iopath && \
 104 | >>>     conda install -c bottler nvidiacub && \
 105 | >>>     conda install pytorch3d -c pytorch3d
 106 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c . /root/.bashrc &&     conda create -n ROMP python==3.8.8 &&     conda activate ROMP &&     conda install -c pytorch pytorch=1.11 torchvision torchaudio cudatoolkit=11.3 &&     conda install -c fvcore -c iopath -c conda-forge fvcore iopath &&     conda install -c bottler nvidiacub &&     conda install pytorch3d -c pytorch3d" did not complete successfully: exit code: 1

```
I don't know how to fix it.

**Comment by JacCubk** [comment]
Hello!


Perhaps you can try changing the Python version of ROMP in the dockerfile and try Python==3.7 or Python=3.8, which may solve your problem.&nbsp;


Good luck!




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "apple/ml-neuman"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Oct 4, 2023 08:12 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [apple/ml-neuman] Dockerfile might need editing for cuda-pytorch compatibility (Issue #29)





 
Hi, thanks for sharing. I have used your file, but it comes out like this:
 Traceback (most recent call last):   File "/usr/lib/python3.8/py_compile.py", line 215, in <module&gt;     sys.exit(main())   File "/usr/lib/python3.8/py_compile.py", line 207, in main     compile(filename, doraise=True)   File "/usr/lib/python3.8/py_compile.py", line 172, in compile     importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)   File "<frozen importlib._bootstrap_external&gt;", line 186, in _write_atomic PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/__pycache__/__future__.cpython-38.pyc.140566495211168' dpkg: error processing package python3.8-minimal (--configure):  installed python3.8-minimal package post-installation script subprocess returned error exit status 1 Errors were encountered while processing:  python3.8-minimal E: Sub-process /usr/bin/dpkg returned an error code (1)  
I don't know how to fix it.
