### ISSUE TITLE
Some confusion about `solve_scale` function in `export_alignment.py`

### ISSUE THREAD

**Issue by yijicheng** [apple/ml-neuman#3]
Thanks for your excellent work!

The first question is that what `right/coe` means in https://github.com/apple/ml-neuman/blob/148ad8f5898ff853b1a5a50779d31c1ea5941b3a/preprocess/export_alignment.py#L124

The second question is that whether `c*(jx*T01+jy*T12+jz*T22)` should be revised to `c*(jx*T02+jy*T12+jz*T22)` in https://github.com/apple/ml-neuman/blob/148ad8f5898ff853b1a5a50779d31c1ea5941b3a/preprocess/export_alignment.py#L122

**Comment by jiangwei221** [comment]
Yes, you are right about the revision. Following is a fixed version:
```python
def solve_scale(joints_world, cap, plane_model):
    cam_center = cap.cam_pose.camera_center_in_world
    a, b, c, d = plane_model
    scales = []
    for j in joints_world:
        jx, jy, jz = j
        # from open3d plane model is: a*x + b*y + c*z + d = 0
        # We can convert the scale problem into a ray-plane intersection problem:
        # Shoting a ray from camera center, (c_x, c_y, c_z), passing through joint, (j_x, j_y, j_z), and
        # Intersecting the plane, a*x + b*y + c*z + d = 0, at some point (x, y, z)
        # Let R0 = (c_x, c_y, c_z)
        #     Rd = (j_x-c_x, j_y-c_y, j_z-c_z)
        # The ray can be written as: R(s) = R0 + s * Rd
        # with the plane equation:
        # a*(c_x + s*(j_x-c_x)) + b*(c_y + s*(j_y-c_y)) + c*(c_z + s*(j_z-c_z)) + d = 0
        # s = -(a*c_x + b*c_y + c*c_z + d) / (a*(j_x-c_x) + b*(j_y-c_y) + c*(j_z-c_z))
        # let right = -(a*c_x + b*c_y + c*c_z + d)
        #       coe = a*(j_x-c_x) + b*(j_y-c_y) + c*(j_z-c_z)
        right = -(a*cam_center[0] + b*cam_center[1] + c*cam_center[2] + d)
        coe = a*(jx-cam_center[0]) + b*(jy-cam_center[1]) + c*(jz-cam_center[2])
        s = right / coe
        if s > 0:
            scales.append(s)
    return min(scales)
```

**Comment by yijicheng** [comment]
> Yes, you are right about the revision. Following is a fixed version:
> 
> ```python
> def solve_scale(joints_world, cap, plane_model):
>     cam_center = cap.cam_pose.camera_center_in_world
>     a, b, c, d = plane_model
>     scales = []
>     for j in joints_world:
>         jx, jy, jz = j
>         # from open3d plane model is: a*x + b*y + c*z + d = 0
>         # We can convert the scale problem into a ray-plane intersection problem:
>         # reference: https://education.siggraph.org/static/HyperGraph/raytrace/rayplane_intersection.htm
>         # Shoting a ray from camera center, (c_x, c_y, c_z), passing through joint, (j_x, j_y, j_z), and
>         # Intersecting the plane, a*x + b*y + c*z + d = 0, at some point (x, y, z)
>         # Let R0 = (c_x, c_y, c_z)
>         #     Rd = (j_x-c_x, j_y-c_y, j_z-c_z)
>         # The ray can be written as: R(s) = R0 + s * Rd
>         # with the plane equation:
>         # a*(c_x + s*(j_x-c_x)) + b*(c_y + s*(j_y-c_y)) + c*(c_z + s*(j_z-c_z)) + d = 0
>         # s = -(a*c_x + b*c_y + c*c_z + d) / (a*(j_x-c_x) + b*(j_y-c_y) + c*(j_z-c_z))
>         # let right = -(a*c_x + b*c_y + c*c_z + d)
>         #       coe = a*(j_x-c_x) + b*(j_y-c_y) + c*(j_z-c_z)
>         right = -(a*cam_center[0] + b*cam_center[1] + c*cam_center[2] + d)
>         coe = a*(jx-cam_center[0]) + b*(jy-cam_center[1]) + c*(jz-cam_center[2])
>         s = right / coe
>         if s > 0:
>             scales.append(s)
>     return min(scales)
> ```

Thanks for your detailed explanation!
