### ISSUE TITLE
I hava a new problem

### ISSUE THREAD

**Issue by smallwhite-dragon** [apple/ml-neuman#38]
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 10.73 GiB already allocated; 0 bytes free; 11.27 GiB reserved in total by PyTorch)

**Comment by jiangwei221** [comment]
You can reduce the number of rays per batch, also the number of samples per ray. For example, to use `--samples_per_ray=64`, `--rays_per_batch=1024`. But remember to keep the same value of `samples_per_ray` during the training of the canonical human.

**Comment by smallwhite-dragon** [comment]
Thank you very much，Can I call you in WeiXin？

**Comment by jiangwei221** [comment]
Yeah, sure, send me an email to: jiangwei1993@gmail.com
