### ISSUE TITLE
Can ML-Neuman learn multiple people from the same scene?

### ISSUE THREAD

**Issue by domattioli** [apple/ml-neuman#41]
The paper shows multiple people, learned from separate scenes, reposed within a novel scene, but how does it work when there are two humans in the same training video? Can it segment both humans out for training the scene NeRF and then iteratively apply the Human NeRF method to each individual?

I've tried applying the preprocess routine to a video with two people and the raw masks do not show two segmented humans. I'm still learning how this software works so I'm not sure if this is an error on my part or a limitation of the software.

**Comment by jiangwei221** [comment]
There are more works to be done to support multiple people in a single video, specifically the instance tracking over frames. Once you have the tracked mask, you should be able to extract two human models.
In the current implementation, we always assume only one person in the video, so we discard detection for the second person.
