### ISSUE TITLE
How much cuda memory is required for training？

### ISSUE THREAD

**Issue by wududu123** [apple/ml-neuman#43]
How much cuda memory is required for training？
I only have one rtx3090， it has  24GB memory.
training failed, not enough cuda memory.

**Comment by jiangwei221** [comment]
Both the background model and human model can be trained on RTX3090. I suggest that to use 64 as the number of samples per ray. If you still hit out of memory problems, you can reduce the number of rays per batch.

**Comment by wududu123** [comment]
I opened ape for training。 Training the background used 20G cuda memory.
And I checked the source code, samples_per_ray default is 128.
