### ISSUE TITLE
Problem occured  preprocessing my own video __ SMPL parameters8/10

### ISSUE THREAD

**Issue by KevinzhouCUC** [apple/ml-neuman#54]
The detail is in the picture down below.

![624804f27906884237e2edc9d70c6f6](https://user-images.githubusercontent.com/108639174/201508409-ef5708fb-6180-479e-846e-b08f2c87c8c9.jpg)

I've been following the bash file  ./run.sh
The problem occurs when using the tuned model ROMP_HRNet32_V1.pkl

Processed 0 / 23 images
Then it terminates. I really have no idea what to do. Could you please help me out of the situation?

**Comment by jiangwei221** [comment]
In our release, we used a specific version of ROMP(f1aaf0c1d90435bbeabe39cf04b15e12906c6111) + specific weights, as hardcoded in the Docker file and bash file.
If you want to use the latest ROMP, you probably need to make sure the latest ROMP export the same data format as ours.

**Comment by KevinzhouCUC** [comment]
I've retried with the ROMP version and strictly followed the docker file and bash file,  but still the same. Is 'missing parameters' a normal phenomenon or it's a problem about loading the model pkl?  
I don't think this step exported anything useful cuz step 9&10 has AssertionError.
Or maybe the video I use didn't meet the requirements...

**Comment by jiangwei221** [comment]
What is your GPU model?

**Comment by jiangwei221** [comment]
The batch size is 32, your 23 images should be done in one inference. Maybe check the output folder?

**Comment by KevinzhouCUC** [comment]
I changed the video file and the problem solved.  Weird problems occur if the video failed to meet requirements. In my situation, camera didn't make a obvious move with human.
