### ISSUE TITLE
Question about method vertex_forward

### ISSUE THREAD

**Issue by buaacyw** [apple/ml-neuman#55]
Thanks for your great work.
I have a question about this [method](https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/preprocess/optimize_smpl.py#L105).
![image](https://user-images.githubusercontent.com/52091468/201818875-41649bff-3bbd-457c-bff4-188e4f708e13.png)

In this method, to get world_verts, da_pose_verts are first transformed by mesh_transf. But I think this equivalent to directly use pose_verts. In code :
`   mesh_transf @ da_pose_verts)`
 is equivalent to 
```
    pose_verts, _= body_model(return_tensor=True,
                                               return_joints=True,
                                               poses=pose[None],
                                               betas=betas[None],
                                               transl=torch.zeros([1, 3]).float().to(device),
                                               )
```
I have checked this by debugging.
So I'm really confused, is this redundancy? Thanks!

**Comment by jiangwei221** [comment]
Yes, I think you are right. The `da_smpl` here is actually just a T-pose. The `body_model` here should be enough.

**Comment by jiangwei221** [comment]
Except you need to correctly handle the `scale`?

**Comment by buaacyw** [comment]
> Except you need to correctly handle the `scale`?

Thanks for your quick reply!
But why do I need to handle the ‘scale’? I think it's fine to leave the code about scale unchanged.
