### ISSUE TITLE
The model seems to not be regressing the texture correctly

### ISSUE THREAD

**Issue by Alexdruso** [apple/ml-neuman#56]
Hello, I am incurring in some problems while training your model. From tensorboard, it looks like the model is unable to correctly regress the color of the canonical human, either predicting black or white regions. 
At first I thought it was my own data, but now I am training on the lab scene and it looks like it's producing the same pattern. Have experienced the same issues during your experiments? Is it just a matter of giving the model more time to converge (for now I trained for max 50-60k iterations) or playing with the hyperparameters?

Thank you very much and nice work!

**Comment by Alexdruso** [comment]
I also want to add that I have tried rendering the posed human learned from my custom data with render_360.py and for some reason it is not rendered in the foreground but in the background far away. May this have to do with the scaling?

**Comment by jiangwei221** [comment]
Hi, Lab scene is more difficult to train in our experience, you can start with seattle or bike scene. 
I don't recall I met the black&white problem, could you share some screenshots?
Do you use `render_360` to render a posed_360 or a canonical_360 video?

**Comment by Alexdruso** [comment]
Hi, thanks for the quick answer. Unfortunately, I cannot share my own data, but tomorrow I will check if the lab scene keeps having the same issue later on in training and I can share it with you in case.

I use both, but if I render the canonical human, then at least the scale and position are fine. When I use render_360 to render the posed human, on the other hand, it is very small and not centered for some reason.

**Comment by Alexdruso** [comment]
I have tried fixing the near/far boundaries and started another experiment now. I will reach back if something changes :)

**Comment by jiangwei221** [comment]
This is how we define the rendering trajectory: https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/render_360.py#L103-L105
What you can do is try to visualize the posed SMPL mesh with the camera trajectory, I personally use https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/utils/utils.py#L164.

**Comment by Alexdruso** [comment]
I have visualized the trajectory with visualize_scene and it looks like the scale of the SMPL mesh varies wildly. Is there any quick way to fix it? I think one possible improvement in the preprocessing step would be to estimate the scale of the human just once. It does not make sense for the size to vary from frame to frame .

**Comment by jiangwei221** [comment]
I see, maybe the plane estimation with RANSAC failed. It requires more work to adapt our preprocessing to a scene with non-planar or texture less ground.

**Comment by Alexdruso** [comment]
Fixing the scale seems to have solved most issues, thanks!

**Comment by jiangwei221** [comment]
Do you have any thoughts why the size varies from frame to frame?

**Comment by Alexdruso** [comment]
Hi, pardon the delay. Visualizing the scene, the estimation of the camera poses from COLMAP was pretty bad and the point cloud was sparse. Rerunning COLMAP and getting better camera poses fixed the issue (the scale still varies, but not dramatically). I still think it would be better to fix the scale through all the frames in order to avoid such issues.
