### ISSUE TITLE
Question about method read_data_to_ram

### ISSUE THREAD

**Issue by buaacyw** [apple/ml-neuman#57]
Thanks for your great work!
I really don't understand what is the below method used for and I haven't found it on the Internet. Could you please help me? Why this can load data to ram? Is this different from directly using self.image? Thanks!
![94bdad3393eccd0cc67da51cc0c6ec4](https://user-images.githubusercontent.com/52091468/203065865-be282b15-808b-4169-943a-4908688be3f2.png)

**Comment by jiangwei221** [comment]
Hi, `self.image` and `self._image` are two different variables. `self._image` is the actual storage of the data, `self.image` is an on-demand property.
In this code, we first call the property to read the image, and store in to `self._image` variable, so it is in the memory.

**Comment by jiangwei221** [comment]
You can simplify it to
```python
self._image = self.image
```

**Comment by buaacyw** [comment]
Thanks! I understand!
