### ISSUE TITLE
About to export .ply file for manul alignmnt

### ISSUE THREAD

**Issue by Spphire** [apple/ml-neuman#66]
For scene, i guess that it should use "data_folder/sparse/points3D.txt or points3D.bin".
but for human pose model, i have no idea about which file should i use to export as .ply.

**Comment by jiangwei221** [comment]
We export the vertices of the posed mesh as ply file, so it's basically a point cloud of human meshes.
You can also refer to https://github.com/apple/ml-neuman/issues/42

**Comment by Spphire** [comment]
> We export the vertices of the posed mesh as ply file, so it's basically a point cloud of human meshes. You can also refer to #42

So, i should generate posed mesh by SFU pose data first?

**Comment by jiangwei221** [comment]
Yes, one trick you can do is add a dummy else branch here with 0 translation, 0 rotation and 1 scaling, https://github.com/apple/ml-neuman/blob/0149d258b2afe6ef65c91557bba9f874675871e4/render_reposing.py#L50-L59
It will give you the posed mesh from a mocap sequence.
The meshes can be obtained from this line: https://github.com/apple/ml-neuman/blob/0149d258b2afe6ef65c91557bba9f874675871e4/render_reposing.py#L144

**Comment by Spphire** [comment]
> Yes, one trick you can do is add a dummy else branch here with 0 translation, 0 rotation and 1 scaling,
> 
> https://github.com/apple/ml-neuman/blob/0149d258b2afe6ef65c91557bba9f874675871e4/render_reposing.py#L50-L59
> 
> 
> It will give you the posed mesh from a mocap sequence.
> The meshes can be obtained from this line:
> https://github.com/apple/ml-neuman/blob/0149d258b2afe6ef65c91557bba9f874675871e4/render_reposing.py#L144

Thanks very much!!
