### ISSUE TITLE
Problem with preprocessing my own video

### ISSUE THREAD

**Issue by WeiYu021** [apple/ml-neuman#78]
In the [**10/10: Optimize SMPL using silhouette**], it got **can not find mvs depth for 00000.png**, 
What does this error message mean?
![problem_pic_4](https://github.com/apple/ml-neuman/assets/92175602/74f57b76-b4be-4109-be16-c2fc0063a86e)

Hope to be corrected, thank you!!!

**Comment by WeiYu021** [comment]
I miss some process and I've find them. Notice that these process will automically use all the gpus, so it would be better to add CUDA_VISIBLE_DEVICES

**Comment by vaneezam** [comment]
Can you please tell how you resolved this issue? What process did you miss?

**Comment by Tiandishihua** [comment]
> In the [**10/10: Optimize SMPL using silhouette**], it got **can not find mvs depth for 00000.png**, What does this error message mean? ![problem_pic_4](https://private-user-images.githubusercontent.com/92175602/238409755-74f57b76-b4be-4109-be16-c2fc0063a86e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjA5NDcsIm5iZiI6MTcxMTUyMDY0NywicGF0aCI6Ii85MjE3NTYwMi8yMzg0MDk3NTUtNzRmNTdiNzYtYjRiZS00MTA5LWJlMTYtYzJmYzAwNjNhODZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA2MjQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhY2EwODVhYmIxNmRlMDUwZjZlOWViYjM0YTc1NDEwMTMwYTI1ZmRlYTI1Yjk5ZmEwZDEzMTg5ZDVmNzk4Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UHZb6EBdZO_JIm4S0wswKA-6Dwk0cl3J6oPBIUZ-Wx0)
> 
> Hope to be corrected, thank you!!!

请问我的推理结果是全黑色的，你有遇到过吗
