### ISSUE TITLE
Questions about data preprocessing

### ISSUE THREAD

**Issue by litchisea** [apple/ml-neuman#84]
Hello, thank you very much for your excellent work!
 When I run docker build -t neuman . ,I get the error。
Is there a problem with the specific version of colmap 96d4ba0b55c0d1f98c8c432420ecd6540868c398? Can I delete this line or use the original version of colmap or have any other solutions, thank you very much.
<img width="522" alt="84fec4cf8b43f6da1733f4bd07f2053" src="https://github.com/apple/ml-neuman/assets/106635715/d6ddfb9d-f9a5-4d6f-b70f-11764f8dfa6c">

**Comment by jiangwei221** [comment]
Yes, I think you can delete the checkout and try to build
