### ISSUE TITLE
为什么我运行demo生成的图像都是黑色的？

### ISSUE THREAD

**Issue by hrx20000209** [apple/ml-neuman#88]
由于我的显卡是GTX40系列的，CUDA版本比较新，所以就更新了所有包的内容，然后运行demo的第一个代码，得到的一直是全黑的图像，请问是什么问题？
`python render_360.py --scene_dir ./data/bike --weights_path ./out/bike_human/checkpoint.pth.tar --mode canonical_360`

**Comment by Tiandishihua** [comment]
> 由于我的显卡是GTX40系列的，CUDA版本比较新，所以就更新了所有包的内容，然后运行demo的第一个代码，得到的一直是全黑的图像，请问是什么问题？ `python render_360.py --scene_dir ./data/bike --weights_path ./out/bike_human/checkpoint.pth.tar --mode canonical_360`

请问你解决了吗？我也是黑色的
